GET http://localhost:8080/authors

###

POST http://localhost:8080/authors 
Content-Type: application/json

{
    "firstname": "David",
    "lastname": "Deschamps"
}

###
POST http://localhost:8080/authors
Content-Type: application/json

{
  "firstname": "Anas",
  "lastname": "Zabili"
}

###
