GET https://linkedout.cleverapps.io/authors

###

POST https://linkedout.cleverapps.io/authors 
Content-Type: application/json

{
  "id": 1,
  "firstname": "David",
  "lastname": "Deschamps"
}

###
POST https://linkedout.cleverapps.io/authors
Content-Type: application/json

{
  "id": 2,
  "firstname": "Anas",
  "lastname": "Zabili"
}

###
