GET http://localhost:8080/authors

###

POST http://localhost:8080/authors 
Content-Type: application/json

{
  "id": 1,
  "firstname": "David",
  "lastname": "Deschamps"
}

###
POST http://localhost:8080/authors
Content-Type: application/json

{
  "id": 2,
  "firstname": "Anas",
  "lastname": "Zabili"
}

###
