GET https://linkedout.cleverapps.io/

###

POST https://linkedout.cleverapps.io/ 
Content-Type: application/json


{
    "name": "Projet de xml",
    "version": 1.0,
    "logo": "https://upload.wikimedia.org/wikipedia/commons/d/df/Université_de_Rouen.png",
    "authors": [
      {
        "id": "1"
      },  {
        "id": "2"
      }
    ]
}